"""empty message

Revision ID: 2f5078974a79
Revises: 354af7f7a819
Create Date: 2019-06-09 20:42:30.370328

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2f5078974a79'
down_revision = '354af7f7a819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
                    sa.Column('order_id', sa.Integer(), nullable=True),
                    sa.Column('place_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
                    sa.ForeignKeyConstraint(['place_id'], ['place.id'], )
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    # ### end Alembic commands ###
