"""empty message

Revision ID: 354af7f7a819
Revises: 837a5600810b
Create Date: 2019-06-09 20:35:30.879654

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '354af7f7a819'
down_revision = '837a5600810b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_status',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('order', sa.Column('status_id', sa.Integer(), nullable=True))
    op.drop_constraint('order_place_id_fkey', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'order_status', ['status_id'], ['id'])
    op.drop_column('order', 'place_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('place_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_place_id_fkey', 'order', 'place', ['place_id'], ['id'])
    op.drop_column('order', 'status_id')
    op.drop_table('order_status')
    # ### end Alembic commands ###
