"""empty message

Revision ID: 53de43db115b
Revises: 5f9aafcce933
Create Date: 2019-06-10 13:57:47.094133

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '53de43db115b'
down_revision = '5f9aafcce933'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'status_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('order', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('order_status', 'order_status_name',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('place', 'place_class',
                    existing_type=postgresql.DOUBLE_PRECISION(precision=53),
                    nullable=False)
    op.alter_column('place', 'place_type_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('place', 'release_date',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    op.alter_column('place', 'taking_date',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    op.alter_column('place_type', 'place_type_name',
                    existing_type=sa.VARCHAR(length=50),
                    nullable=False)
    op.alter_column('user', 'is_admin',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.alter_column('user', 'last_seen',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    op.alter_column('user', 'password_hash',
                    existing_type=sa.VARCHAR(length=128),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password_hash',
                    existing_type=sa.VARCHAR(length=128),
                    nullable=True)
    op.alter_column('user', 'last_seen',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    op.alter_column('user', 'is_admin',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    op.alter_column('place_type', 'place_type_name',
                    existing_type=sa.VARCHAR(length=50),
                    nullable=True)
    op.alter_column('place', 'taking_date',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    op.alter_column('place', 'release_date',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    op.alter_column('place', 'place_type_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('place', 'place_class',
                    existing_type=postgresql.DOUBLE_PRECISION(precision=53),
                    nullable=True)
    op.alter_column('order_status', 'order_status_name',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('order', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('order', 'status_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###
