"""empty message

Revision ID: 5f9aafcce933
Revises: 2f5078974a79
Create Date: 2019-06-09 20:49:46.836404

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5f9aafcce933'
down_revision = '2f5078974a79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_status', sa.Column('order_status_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_status', 'order_status_name')
    # ### end Alembic commands ###
