"""empty message

Revision ID: 837a5600810b
Revises: fe0e35578263
Create Date: 2019-06-09 15:58:32.646505

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '837a5600810b'
down_revision = 'fe0e35578263'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('place_class', sa.Float(), nullable=True))
    op.drop_column('place', 'square')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place',
                  sa.Column('square', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('place', 'place_class')
    # ### end Alembic commands ###
