"""empty message

Revision ID: a66b5467fcb6
Revises: 15f8d89facc0
Create Date: 2019-06-08 01:41:40.478028

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a66b5467fcb6'
down_revision = '15f8d89facc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('place', 'place_type',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('place', 'place_type',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###
