"""empty message

Revision ID: c6a7f00bdfd5
Revises: ee881720a348
Create Date: 2019-06-07 16:41:11.867668

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c6a7f00bdfd5'
down_revision = 'ee881720a348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('taking_date', sa.DateTime(), nullable=True),
                    sa.Column('release_date', sa.DateTime(), nullable=True),
                    sa.Column('place_type', sa.Integer(), nullable=True),
                    sa.Column('square', sa.Float(), nullable=True),
                    sa.Column('price', sa.Float(), nullable=True),
                    sa.ForeignKeyConstraint(['place_type'], ['place_type.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('order',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('place_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('place')
    # ### end Alembic commands ###
