"""empty message

Revision ID: ee881720a348
Revises: a8474207873f
Create Date: 2019-06-07 16:39:40.552544

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ee881720a348'
down_revision = 'a8474207873f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_type',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('place_type_name', sa.String(length=50), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('place_type')
    # ### end Alembic commands ###
