"""empty message

Revision ID: fe0e35578263
Revises: a66b5467fcb6
Create Date: 2019-06-08 02:06:13.716615

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'fe0e35578263'
down_revision = 'a66b5467fcb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('place_type_id', sa.Integer(), nullable=True))
    op.drop_constraint('place_place_type_fkey', 'place', type_='foreignkey')
    op.create_foreign_key(None, 'place', 'place_type', ['place_type_id'], ['id'])
    op.drop_column('place', 'place_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('place_type', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'place', type_='foreignkey')
    op.create_foreign_key('place_place_type_fkey', 'place', 'place_type', ['place_type'], ['id'])
    op.drop_column('place', 'place_type_id')
    # ### end Alembic commands ###
